/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.modelautomobila;

import domain.ModelAutomobila;
import exception.ServerDownException;
import forme.FormMode;
import forme.GlavnaForma;
import forme.modelautomobila.model.ModelTabeleMA;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import sesija.Sesija;

/**
 *
 * @author Nikola
 */
public class FormaPretragaModelaAutomobila extends javax.swing.JDialog {

    /**
     * Creates new form FormaPretragaModelaAutomobila
     */
    public FormaPretragaModelaAutomobila(java.awt.Frame parent, boolean modal) throws ServerDownException {
        super(parent, modal);
        initComponents();
        popuniKombo();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblModeliAutomobila = new javax.swing.JTable();
        panelPretraga = new javax.swing.JPanel();
        komboPolje = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPretraziMA = new javax.swing.JButton();
        btnObrisiFilter = new javax.swing.JButton();
        txtVrednostPretrage = new javax.swing.JTextField();
        btnIzbrisiMA = new javax.swing.JButton();
        btnPrikaziMA = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblModeliAutomobila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblModeliAutomobila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblModeliAutomobilaMouseReleased(evt);
            }
        });
        tblModeliAutomobila.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblModeliAutomobilaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblModeliAutomobila);

        panelPretraga.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga"));

        jLabel1.setText("Izaberite polje:");

        jLabel2.setText("Unesite vrednost:");

        btnPretraziMA.setText("Pretraži");
        btnPretraziMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziMAActionPerformed(evt);
            }
        });

        btnObrisiFilter.setText("Obriši filter");
        btnObrisiFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPretragaLayout = new javax.swing.GroupLayout(panelPretraga);
        panelPretraga.setLayout(panelPretragaLayout);
        panelPretragaLayout.setHorizontalGroup(
            panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretragaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPretragaLayout.createSequentialGroup()
                        .addComponent(btnObrisiFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraziMA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(komboPolje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVrednostPretrage))
                .addGap(22, 22, 22))
        );
        panelPretragaLayout.setVerticalGroup(
            panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretragaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(komboPolje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVrednostPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiFilter)
                    .addComponent(btnPretraziMA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIzbrisiMA.setText("Izbriši model automobila");
        btnIzbrisiMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiMAActionPerformed(evt);
            }
        });

        btnPrikaziMA.setText("Detaljnije");
        btnPrikaziMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziMAActionPerformed(evt);
            }
        });

        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIzbrisiMA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrikaziMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIzbrisiMA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrikaziMA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblModeliAutomobilaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblModeliAutomobilaMouseReleased

        int red = tblModeliAutomobila.getSelectedRow();
        if (red == -1) {
            Sesija.getInstance().getUseCaseParams().put("izabraniMA", null);
            return;
        }
        ModelTabeleMA mtma = (ModelTabeleMA) tblModeliAutomobila.getModel();

        ModelAutomobila ma = mtma.vratimodelURedu(red);
        Sesija.getInstance().getUseCaseParams().put("izabraniMA", ma);
    }//GEN-LAST:event_tblModeliAutomobilaMouseReleased

    private void tblModeliAutomobilaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblModeliAutomobilaPropertyChange

    }//GEN-LAST:event_tblModeliAutomobilaPropertyChange

    private void btnPretraziMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziMAActionPerformed
        ModelTabeleMA mt = (ModelTabeleMA) tblModeliAutomobila.getModel();

        boolean uspesno = mt.prikaziModeleAutomobilaNaOsnovuPretrage(txtVrednostPretrage.getText(), (String) komboPolje.getSelectedItem());
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Pretraga je završena!");
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe modele po zadatoj vrednosti!", "Neuspešna pretraga", JOptionPane.ERROR_MESSAGE);
            obrisiFilter();
        }
    }//GEN-LAST:event_btnPretraziMAActionPerformed

    private void btnObrisiFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiFilterActionPerformed
        obrisiFilter();
    }//GEN-LAST:event_btnObrisiFilterActionPerformed

    private void btnIzbrisiMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiMAActionPerformed
        int red = tblModeliAutomobila.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan model automobila!");
            return;
        }
        ModelTabeleMA mtma = (ModelTabeleMA) tblModeliAutomobila.getModel();

        ModelAutomobila model = mtma.vratiModelAutomobilaURedu(red);
        try {
            String poruka = kontroler.Kontroler.getInstance().izbrisiModelAutomobila(model);
            JOptionPane.showMessageDialog(this, poruka, "Uspešno brisanje", JOptionPane.INFORMATION_MESSAGE);
            mtma.setModeleAutomobila(kontroler.Kontroler.getInstance().vratiModeleAutomobila());
        } catch (ServerDownException se) {
            JOptionPane.showMessageDialog(this, se.getMessage(), "Kraj rada", JOptionPane.WARNING_MESSAGE);
            this.dispose();
            GlavnaForma fr = (GlavnaForma) this.getParent();
            fr.serverZaustavljen();
            return;
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, exception.getMessage(), "Neuspešno brisanje", JOptionPane.ERROR_MESSAGE);
            exception.getMessage();
        }
    }//GEN-LAST:event_btnIzbrisiMAActionPerformed

    private void btnPrikaziMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziMAActionPerformed
        try {
            if (postojiIzabraniModel()) {
                JDialog formaPrikaz = new FormaModelAutomobila(null, true, FormMode.VIEW);
                JOptionPane.showMessageDialog(this, "Odabrani model automobila je pronađen!");
                formaPrikaz.setAlwaysOnTop(true);
                formaPrikaz.setLocationRelativeTo(null);
                formaPrikaz.pack();
                formaPrikaz.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe podatke o modelu!",
                        "Neuspešna pretraga", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ServerDownException se) {
            JOptionPane.showMessageDialog(this, se.getMessage(), "Kraj rada", JOptionPane.WARNING_MESSAGE);
            serverZaustavljen();
        }
    }//GEN-LAST:event_btnPrikaziMAActionPerformed
    private boolean postojiIzabraniModel() {
        if (tblModeliAutomobila.getSelectedRow() == -1) {
            return false;
        }
        return true;
    }
    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnIzbrisiMA;
    private javax.swing.JButton btnObrisiFilter;
    private javax.swing.JButton btnPretraziMA;
    private javax.swing.JButton btnPrikaziMA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox komboPolje;
    private javax.swing.JPanel panelPretraga;
    private javax.swing.JTable tblModeliAutomobila;
    private javax.swing.JTextField txtVrednostPretrage;
    // End of variables declaration//GEN-END:variables

    private void popuniKombo() {
        komboPolje.removeAllItems();
        komboPolje.addItem("Proizvođač");
        komboPolje.addItem("Naziv");
        komboPolje.addItem("Godina nastanka");
        komboPolje.addItem("Tip modela");
    }

    private void srediTabelu() throws ServerDownException {
        ModelTabeleMA mt = new ModelTabeleMA();
        tblModeliAutomobila.setModel(mt);

        tblModeliAutomobila.getColumnModel().removeColumn(tblModeliAutomobila.getColumnModel().getColumn(5));
    }

    private void obrisiFilter() {
        ModelTabeleMA mtabele = (ModelTabeleMA) tblModeliAutomobila.getModel();

        komboPolje.getModel().setSelectedItem("Proizvođač");
        txtVrednostPretrage.setText("");
        mtabele.prikaziModeleAutomobilaNaOsnovuPretrage("", (String) komboPolje.getSelectedItem());
    }

    private void serverZaustavljen() {
        this.dispose();
        GlavnaForma fr = (GlavnaForma) this.getParent();
        fr.serverZaustavljen();
    }
}
